excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gamut-was-taken.github.io
title: Gamut was Taken
email: yltlewvo@eelmail.com
author: Gamut was Taken
description: Situs yang berisi tentang sesuatu yang menarik di dunia ini
paginate: 7
google_analytics: 